### ISSUE TITLE
Support for Cosmos SDK v0.50.x

### ISSUE THREAD

**Issue by jmastr** [forbole/juno#118]
## Feature description 

Support for Cosmos SDK v0.50.x

## Implementation proposal

- Create a `cosmos/v0.50.x` branch
- Bump `module` in `go.mod` to `module github.com/forbole/juno/v6`
- Update `go.mod` to e.g. `github.com/cosmos/cosmos-sdk v0.50.6`
- Fix dependency issues and compilation errors

I could help with the implementation if you like

**Comment by dadamu** [comment]
Done, please try v6 juno

**Comment by jmastr** [comment]
Wow! Thanks!
