### ISSUE TITLE
Why fetching transactions when we have access to all the information in the block

### ISSUE THREAD

**Issue by rach-id** [forbole/juno#43]
Hello,
I have a question concerning the ingestion service. 

In the following line: 
https://github.com/forbole/juno/blob/4f6319e432a544b0866cf62daae4ff2ff6cc9a8e/node/remote/node.go#L145
It is making an RPC request for every transaction in a block. However, I guess that we have access to all that information in the Block structure itself: 
https://github.com/tendermint/tendermint/blob/a185163c5779faaaea9ea29c7c8626c7d26295ca/rpc/coretypes/responses.go#L50

 The reason I am asking these questions is that I am having performance issues with Juno. It is slow and not able to follow up with the chain I am targeting: https://celestia.observer/ 
 Currently, it is missing more than `18000` block...

Thanks,

**Comment by rmontagnin** [comment]
@SweeXordious This is because Tendermint stores the transaction encoded in a different way from what I recall. We might try and see if they can be read directly from the block, although I don't guarantee this will work

**Comment by rach-id** [comment]
I guess if it works, it would speed up the ingestor significantly.
In my case, I added more ingestor services to catchup with the growing chain. So I will close this issue as it no longer reflect a bug but instead an enhancement.
