### ISSUE TITLE
Enqueue stop at the block height that start juno

### ISSUE THREAD

**Issue by APPLECHOI** [forbole/juno#56]
## Bug description

https://github.com/forbole/juno/blob/3b5d944a0def1b47ae695422748c63d263833779/cmd/start/cmd.go#L149
Enqueue missing height stop at `latestBlockHeight`, which would not change when the loop start. So the loop stops after a while where i=latestBlockHeight
And when you call `enqueueNewBlocks` there may be a gap between `latestBlockHeight` and block height so there are missing blocks

## Expected behavior
It should parse forever at that loop. Implementing suitable retry and timeout of node endpoint would also solve the problem.

**Comment by rmontagnin** [comment]
The behavior you are observing is actually correct. Reading the `enqueueMissingBlocks` documentation we see that: 
```
// enqueueMissingBlocks enqueues jobs (block heights) for missed blocks starting
// at the startHeight up until the latest known height.
```

This is wanted, as in order to enqueue (and parse) new blocks we use another method: `enqueueNewBlocks`
https://github.com/forbole/juno/blob/3b5d944a0def1b47ae695422748c63d263833779/cmd/start/cmd.go#L157

This allows to constantly update the `latestBlockHeight` and get all the blocks up until that height.

**Comment by APPLECHOI** [comment]
When the block take longer time to query (more than average block time), It is actually possible to pop out the unprocessed block from the queue when the queue is full. What I suggest is:
1. Add check if the queue is not full
2. Add timeout & retry on parsing block
3. Parse block base on the index height but not subscribe

**Comment by rmontagnin** [comment]
> When the block take longer time to query (more than average block time), It is actually possible to pop out the unprocessed block from the queue when the queue is full. What I suggest is:

Can you please give a detailed example with fake block heights and timings? I would like to understand why this happens in the details of it so that the best solution possible can be applied

**Comment by APPLECHOI** [comment]
I spot this problem because when I start queueing missing block with the latest block heigh++, it won't wait for the block to complete and it enqueue the block height+++, so the latest block height++ never be processed

**Comment by rmontagnin** [comment]
Closing this at it doesn't seem related to Juno anymore
