### ISSUE TITLE
No transactions obtained for Microtickzone-a1 Blockchain

### ISSUE THREAD

**Issue by tristan-oa** [forbole/juno#62]
## Bug description
I tried indexing the Microtick blockchain, specifically the old `microtickzone-a1` chain using an [old Juno fork](https://github.com/forbole/juno/tree/ead810b0ed1e9a71973ba92e0eeb31e41af078a2) (Juno for v0.39.x Cosmos SDK blockchains) and managed to obtain all blocks but no transactions.

This issue was encountered on an [Ubuntu Linux 64-bit 22.04 LTS](https://ubuntu.com/download/desktop) VM running Golang v1.18.1 and PostgreSQL v12.10.

## Steps to reproduce
Prerequisites: Linux VM, Golang and PostgreSQL installed.
1. Fork [this](https://github.com/forbole/juno/tree/ead810b0ed1e9a71973ba92e0eeb31e41af078a2) repo.
2. Follow the setup instructions in the [README file].(https://github.com/forbole/juno/blob/ead810b0ed1e9a71973ba92e0eeb31e41af078a2/README.md).
3. Setup the config file to point to a private node running a copy of _microtickzone-a1_ data. I am connected to a private node running this data, whose details unfortunately cannot be provided.
Note: At the time, `microtickzone-a1` was using **Cosmos SDK v0.34.4-0.20200519133235-d7677e087117**.
4. Run `juno start` and the postgreSQL database should start populating with blocks, but not with transactions.

## Expected behavior
I expect to receive all blocks and transactions for `microtickzone-a1`.

**Comment by tristan-oa** [comment]
So my question would be, what is being done wrong?
Am I running the correct version of Juno to complement the Cosmos version?

**Comment by rmontagnin** [comment]
From what you've detailed inside the issue, it looks like `microtick` is using an even older Cosmos SDK version (`0.34.4`) which we do not support. Please also note that Juno properly supports Cosmos Stargate and above. We do not intend to maintain any support for previous SDK versions as it would be too complicated
